name: Bump Cargo version minor/patch & PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run bump script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: python .github/scripts/bump_version.py --create-pull-request
