name: ci-tests-develop

on:
  pull_request:
    branches: ["develop"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  UV_RESOLUTION_STRATEGY: highest

jobs:
  ci-health-develop:
    name: ci-health-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run ci-health scripts
        run: |
          pip install packaging
          python .github/scripts/version_check.py
          python .github/scripts/commit_emails_check.py

  unittest-develop:
    name: unittest-develop
    needs: [ci-health-develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Rust tests
        run: cargo test --release --verbose

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv with efficient cache
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/*.py.lock
          cache-suffix: os=${{ runner.os }}-py=3.12-res=${{ env.UV_RESOLUTION_STRATEGY }}

      - name: Build and install Python package
        run: uv pip install . --system

      - name: Run Python unittests
        run: python -m unittest discover -s tests/python -v

  unittest-develop-success:
    name: unittest-develop-success
    needs: [unittest-develop]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "All tests passed"
          else
            echo "Some tests failed"
            exit 1
          fi
