name: ci-tests-test

on:
  pull_request:
    branches: ["test"]

env:
  CARGO_TERM_COLOR: always

jobs:
  unittest-test:
    name: unittest-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]
    steps:
      - uses: actions/checkout@v5

      - name: Run Rust tests
        run: cargo test --release --verbose

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Build and install Python package
        run: pip install .

      - name: Run Python unittests
        run: python -m unittest discover -s tests/python -v

  unittest-test-success:
    name: unittest-test-success
    needs: [unittest-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "All tests passed"
          else
            echo "Some tests failed"
            exit 1
          fi
