name: Rust PR Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-pr-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Check crate version on crates.io
        run: |
          python .github/scripts/version_check.py

      - name: Run tests
        run: cargo test --release --verbose
